import os
import sys
import json
import subprocess
import google.generativeai as genai
from github import Github

# --- Config ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_NAME = os.environ.get("REPO_NAME")
ISSUE_NUMBER = int(os.environ.get("ISSUE_NUMBER"))
PROMPT_CONTENT = os.environ.get("PROMPT_CONTENT", "")

# 定义触发关键词列表
TRIGGERS = ["/gemini", "/丹德莱"]

def setup_gemini():
    genai.configure(api_key=GEMINI_API_KEY)
    return genai.GenerativeModel('gemini-2.5-flash')

def get_file_structure(root_dir="."):
    """获取文件结构，忽略无关目录"""
    file_tree = []
    exclude_dirs = {'.git', '.github', '__pycache__', 'site', 'venv'}
    
    for root, dirs, files in os.walk(root_dir):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        for file in files:
            if file.endswith(('.md', '.yml', '.py', '.css', '.txt')):
                path = os.path.join(root, file)
                file_tree.append(path)
    return "\n".join(file_tree)

def run_git_cmd(cmd):
    subprocess.run(cmd, shell=True, check=True)

def main():
    # 1. 检查触发词
    if not PROMPT_CONTENT:
        print("Content is empty. Skipping.")
        sys.exit(0)

    active_trigger = None
    for trigger in TRIGGERS:
        if trigger in PROMPT_CONTENT:
            active_trigger = trigger
            break
    
    if not active_trigger:
        print(f"No triggers found in content. Expected one of: {TRIGGERS}")
        sys.exit(0)

    print(f"检测到触发词: {active_trigger}")

    # 2. 准备上下文
    print("正在分析项目结构...")
    file_tree = get_file_structure()
    
    # 移除触发词，提取真实需求
    user_request = PROMPT_CONTENT.replace(active_trigger, "").strip()
    
    # 3. 构建 Prompt
    system_prompt = f"""
    你是一个专业的文档工程师，正在维护一个基于 MkDocs 的项目。
    
    当前项目的文件结构如下：
    {file_tree}
    
    用户的需求是：
    {user_request}
    
    请根据用户需求，生成需要修改或创建的文件内容。
    
    【重要】请务必只返回一个纯 JSON 格式的列表，不要包含 Markdown 代码块标记（如 ```json）。
    格式如下：
    [
        {{
            "path": "docs/tutorial/new_guide.md",
            "content": "# 新文档标题\\n\\n这里是文档内容..."
        }},
        {{
            "path": "mkdocs.yml",
            "content": "..." 
        }}
    ]
    
    如果是修改 mkdocs.yml，请返回完整的 mkdocs.yml 内容，而不仅仅是修改部分。
    对于 Markdown 文件，请确保内容丰富、格式正确。
    """

    # 4. 调用 Gemini
    print("正在呼叫 Gemini...")
    model = setup_gemini()
    try:
        response = model.generate_content(system_prompt)
        response_text = response.text
        
        # 清理 Markdown 标记
        if response_text.startswith("```json"):
            response_text = response_text[7:]
        if response_text.startswith("```"):
            response_text = response_text[3:]
        if response_text.endswith("```"):
            response_text = response_text[:-3]
            
        changes = json.loads(response_text)
    except Exception as e:
        print(f"Gemini 调用或 JSON 解析失败: {e}")
        # 尝试打印原始文本以便调试
        try:
            print(f"原始返回: {response.text}")
        except:
            pass
        sys.exit(1)

    # 5. 应用更改
    print(f"收到 {len(changes)} 个文件变更请求。")
    
    # 配置 Git 用户
    run_git_cmd('git config --global user.name "Gemini Bot"')
    run_git_cmd('git config --global user.email "gemini-bot@actions.github.com"')
    
    # 创建新分支
    branch_name = f"ai/issue-{ISSUE_NUMBER}-{os.urandom(4).hex()}"
    run_git_cmd(f"git checkout -b {branch_name}")
    
    for change in changes:
        file_path = change['path']
        content = change['content']
        
        # --- 修复点：处理根目录文件 ---
        dir_name = os.path.dirname(file_path)
        if dir_name: # 只有当目录名不为空时才创建目录
            os.makedirs(dir_name, exist_ok=True)
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"已写入: {file_path}")
        
        run_git_cmd(f'git add "{file_path}"')

    # 6. 提交并推送
    try:
        run_git_cmd(f'git commit -m "AI Auto-generated changes for Issue #{ISSUE_NUMBER}"')
        run_git_cmd(f"git push origin {branch_name}")
    except subprocess.CalledProcessError:
        print("没有检测到文件更改，跳过提交。")
        sys.exit(0)

    # 7. 创建 PR
    print("正在创建 Pull Request...")
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(REPO_NAME)
    issue = repo.get_issue(ISSUE_NUMBER)
    
    pr_body = f"This PR was automatically generated by Gemini based on Issue #{ISSUE_NUMBER}.\n\nTrigger: `{active_trigger}`\nRequest: {user_request}"
    
    pr = repo.create_pull(
        title=f"AI: Fix for Issue #{ISSUE_NUMBER}",
        body=pr_body,
        head=branch_name,
        base="main"
    )
    
    # 回复 Issue
    issue.create_comment(f"✅ 指挥官，任务已完成！丹德莱已为您创建了 PR: {pr.html_url}，请查收。")
    print(f"PR Created: {pr.html_url}")

if __name__ == "__main__":
    main()