import os
import sys
import json
import re
import subprocess
import google.generativeai as genai
from github import Github

# --- Config ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_NAME = os.environ.get("REPO_NAME")
ISSUE_NUMBER = int(os.environ.get("ISSUE_NUMBER"))
# Issue正文触发
PROMPT_CONTENT = os.environ.get("PROMPT_CONTENT", "")

# 配置Gemini
def setup_gemini():
    genai.configure(api_key=GEMINI_API_KEY)
    return genai.GenerativeModel('gemini-2.5-flash')

def get_file_structure(root_dir="."):
    """Ignore Files"""
    file_tree = []
    exclude_dirs = {'.git', '.github', '__pycache__', 'site', 'venv'}
    
    for root, dirs, files in os.walk(root_dir):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        for file in files:
            if file.endswith(('.md', '.yml', '.py', '.css', '.txt')):
                path = os.path.join(root, file)
                file_tree.append(path)
    return "\n".join(file_tree)

def run_git_cmd(cmd):
    subprocess.run(cmd, shell=True, check=True)

def main():
    if not PROMPT_CONTENT or "/gemini" not in PROMPT_CONTENT:
        print("No /gemini command found. Skipping.")
        sys.exit(0)

    # 1. Prepare context
    print("正在分析项目结构...")
    file_tree = get_file_structure()
    
    # Remove `/gemini`
    user_request = PROMPT_CONTENT.replace("/gemini", "").strip()
    
    # 2. Prompt
    system_prompt = f"""
    你是一个专业的文档工程师，正在维护一个基于 MkDocs 的项目。
    
    当前项目的文件结构如下：
    {file_tree}
    
    用户的需求是：
    {user_request}
    
    请根据用户需求，生成需要修改或创建的文件内容。
    
    【重要】请务必只返回一个纯 JSON 格式的列表，不要包含 Markdown 代码块标记（如 ```json）。
    格式如下：
    [
        {{
            "path": "docs/tutorial/new_guide.md",
            "content": "# 新文档标题\\n\\n这里是文档内容..."
        }},
        {{
            "path": "mkdocs.yml",
            "content": "..." 
        }}
    ]
    
    如果是修改 mkdocs.yml，请返回完整的 mkdocs.yml 内容，而不仅仅是修改部分。
    对于 Markdown 文件，请确保内容丰富、格式正确。
    """

    # 3. Gemini
    print("正在呼叫 Gemini...")
    model = setup_gemini()
    try:
        response = model.generate_content(system_prompt)
        response_text = response.text
        
        # Clean up any existing Markdown tags
        if response_text.startswith("```json"):
            response_text = response_text[7:]
        if response_text.startswith("```"):
            response_text = response_text[3:]
        if response_text.endswith("```"):
            response_text = response_text[:-3]
            
        changes = json.loads(response_text)
    except Exception as e:
        print(f"Gemini 调用或 JSON 解析失败: {e}")
        print(f"原始返回: {response.text if 'response' in locals() else 'None'}")
        sys.exit(1)

    # 4. Apply changes
    print(f"收到 {len(changes)} 个文件变更请求。")
    
    # Config git User
    run_git_cmd('git config --global user.name "Gemini Bot"')
    run_git_cmd('git config --global user.email "gemini-bot@actions.github.com"')
    
    # Create new branch
    branch_name = f"ai/issue-{ISSUE_NUMBER}-{os.urandom(4).hex()}"
    run_git_cmd(f"git checkout -b {branch_name}")
    
    for change in changes:
        file_path = change['path']
        content = change['content']
        
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"已写入: {file_path}")
        
        run_git_cmd(f'git add "{file_path}"')

    # 5. Push
    try:
        run_git_cmd(f'git commit -m "AI Auto-generated changes for Issue #{ISSUE_NUMBER}"')
        run_git_cmd(f"git push origin {branch_name}")
    except subprocess.CalledProcessError:
        print("没有检测到文件更改，跳过提交。")
        sys.exit(0)

    # 6. PR
    print("正在创建 Pull Request...")
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(REPO_NAME)
    issue = repo.get_issue(ISSUE_NUMBER)
    
    pr_body = f"This PR was automatically generated by Gemini based on Issue #{ISSUE_NUMBER}.\n\nRequest: {user_request}"
    
    pr = repo.create_pull(
        title=f"AI: Fix for Issue #{ISSUE_NUMBER}",
        body=pr_body,
        head=branch_name,
        base="main"
    )
    
    # Replay on Issue
    issue.create_comment(f"✅ 任务已完成！我已为您创建了 PR: {pr.html_url}，请查收。")
    print(f"PR Created: {pr.html_url}")

if __name__ == "__main__":
    main()